package name.paulevans.junk.laundrysystem.listener;

import name.paulevans.junk.laundrysystem.event.DryerMachineAddedEvent;
import name.paulevans.junk.laundrysystem.event.NewFolderAddedEvent;
import name.paulevans.junk.laundrysystem.event.NewWetClothesProducerAddedEvent;

/**
 * <p>Listens for events generated by the laundy system object</p>
 * 
 * @author Paul R Evans
 * @version $Id$
 *
 */
public interface LaundrySystemListener {
	
	/**
	 * <p>Callback for when a new 'folder' is added to the system</p>
	 * 
	 * @param pEvent
	 */
	void newFolderAdded(NewFolderAddedEvent pEvent);
	
	/**
	 * <p>Callback for when a new 'wet clothes producer' is added to the
	 * system</p>
	 * 
	 * @param pEvent
	 */
	void newWetClothesProducerAdded(NewWetClothesProducerAddedEvent pEvent);
	
	/**
	 * <p>Callback when when the dryer machine is added to the system</p>
	 * 
	 * @param pEvent
	 */
	void dryerMachineAdded(DryerMachineAddedEvent pEvent);
}
