<?xml version="1.0"?>

<!-- Defines a SOAP binding and service for the transaction identifier operations -->
<definitions 
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:TxnIdCommands="http://name.paulevans/samples/TransactionIdentifier-commands"
	xmlns:definitions="http://name.paulevans/samples/TransactionIdentifier-service-definitions"
	xmlns:tns="http://name.paulevans/samples/TransactionIdentifier/services"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	targetNamespace="http://name.paulevans/samples/TransactionIdentifier/services">

	<!-- Import the TransactionIdentifier abstractions (types, messages, and port types) --> 
	<import namespace="http://name.paulevans/samples/TransactionIdentifier-service-definitions"
		location="TransactionIdentifier-abstract.wsdl" />

	<!-- Define the bindings -->
	<binding name="TransactionIdentifierBinding"
		type="definitions:TransactionIdentifierPortType">

		<!-- we're going to use the SOAP binding and describe all 
			 contained operations to use a style: document -->
		<soap:binding style="document" 
			transport="http://schemas.xmlsoap.org/soap/http" />

		<!-- Defines our concrete transaction identifier generation operation -->
		<operation name="GenerateTransactionIdentifier">

			<!-- Specify this operation as being document-oriented (using
				 the style attribute here is redundant because we already 
				 defined the operation-style using the <soap:binding> element 
				 up above  -->
			<soap:operation style="document"
				soapAction="http://name.paulevans/samples/action/AnyCommand" />

			<input>
				<!-- SOAP extensibility element to specify the soap body of 
					 the input (request) message -->
				<soap:body parts="body" use="literal" />
			</input>
			<output>
				<!-- Define the soap body of the output (response) message -->
				<soap:body parts="body" use="literal" />
			</output>
		</operation>
	</binding>

	<!-- the concrete service definition -->
	<service name="TxnIdGeneratorService">
		<!-- Associate a binding with a network endpoint -->
		<port name="TransactionIdentifierPort" binding="tns:TransactionIdentifierBinding">
			<soap:address location="/" />
		</port>
	</service>
</definitions>
