package name.paulevans.junk.model.listener;

import name.paulevans.junk.model.event.FoldedEvent;

/**
 * <p>Listens for events generated by articles of clothing (weird, eh?).</p>
 * 
 * @author Paul R Evans
 * @version $Id$
 *
 */
public interface ClothingArticleListener {
	
	/**
	 * <p>Callback for when an article of clothing is folded</p>
	 * 
	 * @param pEvent
	 */
	void clothingArticleFolded(FoldedEvent pEvent);

}
