package name.paulevans.junk.model.listener;

import name.paulevans.junk.model.event.ClothingArticleEvent;
import name.paulevans.junk.model.event.DryerMachineEvent;

/**
 * <p>Listens for events generated by the dryer machine</p>
 * 
 * @author Paul R Evans
 * @version $Id$
 *
 */
public interface DryerMachineListener {
	
	/**
	 * <p>Callback for when an article of clothing is added to the dryer
	 * machine</p>
	 * 
	 * @param pEvent
	 */
	void clothingArticledAdded(ClothingArticleEvent pEvent);
	
	/**
	 * <p>Callback for when an article of clothing is removed from the dryer
	 * machine</p>
	 * 
	 * @param pEvent
	 */
	void clothingArticleRemoved(ClothingArticleEvent pEvent);
	
	/**
	 * <p>Callback for when a dryer machine becomes activated</p>
	 * 
	 * @param pEvent
	 */
	void dryerMachineActivated(DryerMachineEvent pEvent);
	
	/**
	 * <p>Callback for when a dryer machine is deactivated</p>
	 * @param pEvent
	 */
	void dryerMachineDeactivated(DryerMachineEvent pEvent);

}
